create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(10, 2) not null check (price >= 0),
  description text not null,
  image text not null,
  tag text not null default 'New today',
  available boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.categories (name)
values ('Birthday'), ('Anniversary'), ('Marriage'), ('Holud'), ('Gifts')
on conflict (name) do nothing;

alter table public.categories enable row level security;
alter table public.products enable row level security;

create policy "Public can read categories"
  on public.categories for select using (true);

create policy "Public can manage categories"
  on public.categories for all using (true) with check (true);

create policy "Public can read products"
  on public.products for select using (true);

create policy "Public can manage products"
  on public.products for all using (true) with check (true);